CREATE DATABASE BookShop
Use BookShop
 Create Table books
 (
   ID INT,
   NAME VARCHAR(30) NOT NULL,
   AUTHORNAME VARCHAR(50) DEFAULT 'UNKNOWN' ,
   PAGECOUNT  INT CHECK(PAGECOUNT>10),
   PRICE FLOAT CHECK(PRICE>3)
 );
  INSERT INTO books VALUES
  (1,'SENAN','ASR',40,35),
  (2,'ELXAN','TXTTT',70,80),
  (3,'SEND','Geroge',65,30);
  SELECT * FROM books
  WHERE AUTHORNAME='GEROGE';
  DELETE FROM books WHERE (PRICE<30);
  
 
